title: Humanities Without Walls Career Diversity Toolkit
description: Resources and information for graduate students intending to work outside academia
theme: just-the-docs

color_scheme: dark

logo: "/assets/images/site_logo.png"

url: https://hwwcommunityengagedresearch.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
